### PR TITLE
Fix consecutive area info bug, update item buffers to use chunks instead

### PR DESCRIPTION
**Pull request by Bird-Bird**
Fixed a bug where using duplicate and paste actions with areas that do/may overlap cause a crash.
Updated item buffers to use chunks instead.

### CODE REVIEW

**Comment by GoranKovac** [comment]
Can you point me to the bug, how to reproduce it? Why are we updating table before job (since the data is not changed prior job)?

**Comment by Bird-Bird** [comment]
Behaviour when commenting out the fix:
kp6ZGq3Ix9
As jobs of the areas are processed sequentially if job of one area updates the area of another job the selection info needs to be updated.

**Comment by GoranKovac** [comment]
Oh, that is something I want to fix - prevent drawing overlaps

**Comment by Bird-Bird** [comment]
I cannot think of many practical uses either, perhaps it could be useful when you want to strip out /copy an area from the section you are working on without losing your selection.
mGwVrL2KEX

**Pull request merged**
