### PR TITLE
adds API/item based method to store items with instead of track chunks

### PR DESCRIPTION
**Pull request by Lazzle**
Hi, this one doesn't do anything with track chunks any more. It's storing tables of item chunks per track now. I've lightly tested it and it seems to work okay.

I've commented out the check for the same state in the Save Button function because that won't work any more. Need to have a think about how to check for duplicates... it's a shame there isn't an item hash function in the API.

### CODE REVIEW

**Comment by GoranKovac** [comment]
it seem to have some errors.If any item is missing,copied,added on another
track ,the script won't work.

**Comment by Lazzle** [comment]
Oh yeah, it works wonderfully with one track though. :)

Just close this one and I'll have a look later.

**Comment by GoranKovac** [comment]
yeah :) how do i do that? I'm new to this git hub thing

**Comment by Lazzle** [comment]
It was me using CountMediaItems instead of CountTrackMediaItems... another pull request coming up.

**Pull request closed without merging**
