### PR TITLE
Add item buffers, refactor AreaDo

### PR DESCRIPTION
**Pull request by Bird-Bird**
I kept the old AreaDo function as AreaDo_old, as every job would have to be rewritten to use buffers it made more sense rewrite the function to me.

(It would perhaps be possible to implement it into the old AreaDo function but I couldn't get deleting to work reliably, it also felt limited for the future if we need to tweak the behaviour of the jobs)

### CODE REVIEW

**Comment by Bird-Bird** [comment]
NjDIhprTPN
Copying/Moving/Splitting/Deleting/Duplicating, haven't figured out how to get paste mode to work yet.

**Comment by GoranKovac** [comment]
Reviewing the code and refactoring, improving:
Lots of things can be written more simple
Some can reuse old functions with minor modifications
Some functions in general can be refactored to your functions (some of yours are simpler and easier to understand than mine)

Will upload for testing after I refactor it

**Comment by Bird-Bird** [comment]
👍 

On the topic of keeping items in buffers and replicating them, do you think it would be too slow to copy item state chunks? 
I am finding that as you tweak lots of item properties, add take envelopes, take FX, external state to items it gets harder and harder to replicate them manually.

**Comment by GoranKovac** [comment]
Yeah chunking is a way to go, we already have code that grabs chunks we need to improve it.
When item is created it is empty and it needs chunk which we clone them from source. Thats how copy works

**Comment by Bird-Bird** [comment]
Testing copy/pasting item state chunks instead of replicating manually, and seems to be pretty quick, for over a hundreds of items with take envelopes and a JS take FX:
2QV9XMf9hB

**Comment by GoranKovac** [comment]
I'm almost finished, just trying to figure out why copy mode is broken. Code is drastically reduced

**Comment by GoranKovac** [comment]
And please do not add any drastic changes to your code/brantch now until I finish this since the buffer code is different now so we don't have to port every new feature to again new behavior

**Comment by GoranKovac** [comment]
DEV branch updated, PR is not directly merged since it was refactored. As far as I've tested it behaves EXACTLY like your gifs above, did not encountered any error.

Reused old functions with modifications (specifically split delete function since it does the job fine).
Simplified copy buffer code etc.
Please test!

BTW Latest DEV branch has many more fixes as you can see from commit history.

**Comment by Bird-Bird** [comment]
Testing, everything seems to be working fine in the DEV branch, there are a few bugs I came across, copying item chunks will solve some of them.
For the others creating new issues on GitHub.

**Pull request closed without merging**
