### PR TITLE
Move moving inside jobs

### PR DESCRIPTION
**Pull request by Bird-Bird**
I made it so dragging an area does not update the start position of the area while dragging, it is the only way I was able to move it inside **AreaDo()** jobs. When I think about it makes sense to me (The area that is being dragged is a visual representation of what is going to happen, but the area is still actually where it is being dragged from)

### CODE REVIEW

**Comment by Bird-Bird** [comment]
upiLfV1g06
Still need to handle overlaps.

**Comment by GoranKovac** [comment]
I have pushed the update that resolves this issue, only thing we need to see is are we going to delete the AREA section or the ITEM section:

If the Area is larger than item under it it will delete that AREA from target item

**Comment by Bird-Bird** [comment]
Will test it.

I have been playing around with refactoring the copy paste behaviour a bit to see if the implementations with replacing areas could be made much simpler. So in this case, moving would be something like:
* store items and the envelopes in the area in a buffer
* delete everything in source area
* delete everything in target area
* paste items and envelopes from the buffer to the target area
That way overlaps would be handled automatically without any issues.

Currently items/envelopes are created/pasted in one go in the **paste()** functions in **Area51_API_Functions**, which makes it harder to implement various types of behaviour like this.

**Comment by GoranKovac** [comment]
With this update I've pushed it does exactly that, it deletes everything in target area, and then creates source items there

**Comment by GoranKovac** [comment]
Can you open this issue till we resolve it?

**Comment by Bird-Bird** [comment]
I have gathered some screencaps of various implementations. When moving Cubase, Ableton and Studio One seem to be replacing only the overlapping parts of the dragged area, the other items in the target area remain intact. 

3ZZoinAeHw
m2EXVRcRFA
DQ1C88ypVr

I believe muting / removing the overlap in some form is superior as it lets the user directly select what they want and place it wherever they want like the implementations above.

**Comment by Bird-Bird** [comment]
Just tested your implementation, it behaves more ''correct'' than the implementations I screencapped, to me. But i am not sure if there is a reason they split the items at the overlaps, perhaps people on the forums would have a better answer?

**Comment by GoranKovac** [comment]
There is now one major issue with my implementation, and its that if you move Area so the target is still  above source it will remove the source AND target items and crash. Basically it would delete the Area

**Comment by GoranKovac** [comment]
Hm.. got an idea.  We can turn on "TRIM CONTENT BEHIND MEDIA WHEN EDITING" and when the loop passes turn it of. That way we will have the desired behavior

**Comment by Bird-Bird** [comment]
I have thought of it, but I am not sure if we can restore the original setting the user has, this was one of the reasons I wanted to refactor the code a bit to have the items copied from a temporary buffer instead of directly copying them from arrangement in one pass.

**Comment by GoranKovac** [comment]
It is practically easy to do, store the initial setting when script starts. But your solution is more practical, because we would need to constantly check the that flag, turn it on,off,off on,etc etc

**Comment by Bird-Bird** [comment]
BkiX2xBP07
Testing buffer based job behaviour. Seems to work fine so far. Still haven't implemented buffers for envelopes, also some parts a bit messy. Will have to cleanup and implement them before I make a pull request.

**Comment by GoranKovac** [comment]
Looks great! clean that one up and make PR. I will take a look and help make Envelope buffer

**Pull request merged**
